- id: Sunset
  alias: Turn on the lights when the sun sets
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunset
  action:
    service: light.turn_on


- id: HA_start
  alias: "Notify when Home Assistant Starts"
  trigger:
    - platform: homeassistant
    # Event can also be 'shutdown'
      event: start
  action:
    - service: notify.notify
      data:
        title: "Start"
        message: "Home Assistant Started"

- id: HA_shutdown
  alias: "Notify when Home Assistant Shutsdown"
  trigger:
    platform: homeassistant
    # Event can also be 'shutdown'
    event: shutdown
  action:
  - service: notify.notify
    data:
      title: "Shutdown"
      message: "Home Assistant Shutdown"
